client/src/containers/organisms/ActiveTask.js
client/src/containers/organisms/CompletedTask.js
client/src/containers/pages/ActiveTaskList.js
client/src/containers/pages/CompletedTaskList.js

class-based component を functional component に作り替えた

---

client/.eslintrc.json
client/package.json
client/src/containers/organisms/ActiveTask.js
client/src/containers/organisms/CompletedTask.js
client/src/containers/organisms/header.js
client/src/containers/pages/ActiveTaskList.js
client/src/containers/pages/CompletedTaskList.js

既存のコンポーネントにPropTypesを定義

---

client/src/containers/organisms/CompletedTask.js
client/src/containers/pages/ActiveTaskList.js
client/src/containers/pages/CompletedTaskList.js

コンポーネントのstyling方法をStyledComponentsに統一

---

client/src/containers/atoms/Button.js

Buttonコンポーネントにpropsが渡るように修正

---

client/.eslintrc.json
client/package-lock.json
client/package.json
client/src/App.js
client/src/containers/atoms/Button.js
client/src/containers/organisms/ActiveTask.js
client/src/containers/organisms/CompletedTask.js
client/src/containers/organisms/header.js
client/src/containers/pages/ActiveTaskList.js
client/src/containers/pages/CompletedTaskList.js
client/src/index.js
client/src/modules/TaskModel.js
client/src/modules/activeTaskModule.js
client/src/modules/completedTaskModule.js
client/src/store.js

eslintでimport文を自動ソートできるようにする

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/containers/atoms/Button.js
client/src/containers/organisms/header.js
client/src/containers/organisms/mobileHeader.js
client/src/containers/pages/ActiveTaskList.js
client/src/containers/pages/CompletedTaskList.js
client/src/containers/pages/MobileActiveTaskList.js
client/src/containers/pages/MobileCompletedTaskList.js

レスポンシブデザインの仕組みを導入

---

README.md

READMEにステータスバッジを追加

---

client/package-lock.json
client/package.json
client/src/modules/activeTaskModule.js
client/src/modules/completedTaskModule.js
client/src/store.js

react-starter-kitの新しいバージョンをinstall

---

client/src/containers/pages/ActiveTaskList.js

タブを切り替えても検索条件がリセットされないようにする

---

client/src/containers/organisms/ActiveTask.js
client/src/containers/pages/ActiveTaskList.js

PropTypesのwarningを解消

---

client/src/containers/pages/CompletedTaskList.js
client/src/containers/pages/MobileCompletedTaskList.js
client/src/modules/completedTaskModule.js

完了タスク一覧画面にも検索機能を実装する

---

client/src/containers/organisms/ActiveTask.js

border-color の判定ロジックを修正

---

.github/workflows/nodejs.yml

ビルドステップを削除

---

client/public/service-worker.js
client/src/App.js
client/src/components/atoms/Button.js
client/src/components/organisms/ActiveTask.js
client/src/components/organisms/CompletedTask.js
client/src/components/organisms/Header.js
client/src/components/organisms/MobileHeader.js
client/src/components/pages/ActiveTaskList.js
client/src/components/pages/CompletedTaskList.js
client/src/components/pages/MobileActiveTaskList.js
client/src/components/pages/MobileCompletedTaskList.js
client/src/const.js
client/src/db.js
client/src/history.js
client/src/index.js
client/src/modules/TaskModel.js
client/src/modules/activeTaskModule.js
client/src/modules/completedTaskModule.js
client/src/setupTests.js
client/src/store.js
client/test/Button.test.js

grep -rl "'use strict';" ./ | xargs sed -i.bak -e 's/'use strict';//g'
で検索して置換した。
行頭に空白行ができているがよいか?

[fix]#38'use strict'を削除する #38

---

client/src/components/atoms/SearchBox.js
client/src/components/pages/ActiveTaskList.js
client/src/components/pages/CompletedTaskList.js

検索ボックスをコンポーネント化

---

client/package.json

eslintの設定を変更

---

client/.eslintrc.json
client/package-lock.json
client/package.json

webpack-mergeをdevDependenciesに移動する

---

client/package-lock.json
client/package.json
client/src/components/atoms/Button.tsx

ButtonコンポーネントをTypeScript化

---

client/src/components/organisms/ActiveTask.js
client/src/components/organisms/CompletedTask.js
client/src/utils/taskUtil.ts
client/webpack.common.js

#16 #2 
webpackで拡張子が.tsのファイルをトランスパイルできるように、webpackの設定を変更。

時間表示のメソッドを共通化

---

client/src/components/atoms/SearchBox.tsx

typescriptize SearchBox

---

client/package-lock.json
client/package.json
client/test/Button.test.tsx

testファイルをTypeScript化
